export * from './AsignaturaService';
export * from './AuthService';
export * from './BaseService';
export * from './SeccionService';
export * from './CampusService';
export * from './DocenteService';
export * from './EdificioService';
export * from './horarioService';
export * from './SalaService';
