from .base import Repository
from .docente_repo import DocenteRepository
from .asignatura_repo import AsignaturaRepository
from .seccion_repo import SeccionRepository
from .sala_repo import SalaRepository
from .edificio_repo import EdificioRepository
from .campus_repo import CampusRepository
from .clase_repo import ClaseRepository
from .restriccion_repo import RestriccionRepository
from .reporte_repo import ReporteRepository
from .reportehoras_repo import ReporteDetalleHorasRepository
from .bloque_repo import BloqueRepository
